stages:
  - build
  - test
  - master

build-job:  
  stage: build
  tags:
    - nataprueba-back-natadev    # This job runs in the build stage, which runs first.
  script:    
    - echo "Creacion Carpeta"
    - mkdir NataFolder
    - echo "Finalizando Creacion carpeta Creacion-Aplicacion binary" > NataFolder/executable-binary-file-v1

first-test-job:
  stage: test
  tags:
    - nataprueba-back-natadev
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - mkdir NataFolder
    - sleep 60
    - echo "Code coverage is 90%"
    - cat NataFolder/executable-binary-file-v1

deploy-job:
  stage: master 
  script:
    - cd /var/www/mios/mios-backend/pruebasnata-back-v2
    - echo "Deploying application..."
    - git status
    - echo "Application successfully deployed."
  tags:
    - nataprueba-back-natadev

