stages:
  - build
  - test
  - master

build-job:  
  stage: build
  tags:
    - nataprueba-back-nata  
  script:    
    - echo "Compiling the Code"
    - echo "Compile complete"
    - mkdir NataFolder/
    - echo "My Aplicacion binary file" > NataFolder/executable-binary-file-v1
  artifacts:
    paths:
      - NataFolder/executable-binary-file-v1  

first-test-job:
  stage: test
  tags:
    - nataprueba-back-nata 
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    #- mkdir NataFolder
    #- sleep 60
    - echo "Code coverage is 90%"
    - cat $CI_PROJECT_DIR/NataFolder/executable-binary-file-v1

deploy-job:
  stage: master 
  tags:
    - nataprueba-back-nata 
  script:
    #- cd /var/www/mios/mios-backend/pruebasnata-back-v2
    - echo "Deploying application..."
    #- git status
    - echo "Application successfully deployed."
  #tags:
  #  - nataprueba-back-nata  

